name: ros
description: "ROS - Roshan Operating System: Advanced professional modern Termux-like app with AI integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Core UI Framework
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Storage and Database
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # HTTP and API Integration
  http: ^1.2.1
  
  # File Management and I/O
  crypto: ^3.0.3
  
  # Device Info and System
  device_info_plus: ^10.1.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Theme and UI Components
  flex_color_scheme: ^7.3.1
  lottie: ^3.1.2
  
  # Terminal Fonts
  google_fonts: ^6.2.1
  
  # Screen Management
  wakelock_plus: ^1.2.5
  
  # Navigation
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/
    - assets/termux/
    - assets/ai/
    - assets/sounds/
    - assets/packages/
    - assets/scripts/
    - assets/themes/
    - assets/splash/
    - assets/tutorials/